name: 'actions/version'
description: 'Create and share version.txt file'
outputs:
  version:
    description: "version number"
    value: ${{ steps.reading-version.outputs.version }}

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - id: project_type
      uses: yadickson/actions-steps/project-type@v1

    - if: ${{ steps.project_type.outputs.type }} == 'node'
      uses: yadickson/actions-steps/project-version/node@v1

    - if: ${{ steps.project_type.outputs.type }} == 'python'
      uses: yadickson/actions-steps/project-version/python@v1

    - uses: yadickson/actions-steps/cache-version@v1

