name: 'actions/version'
description: 'Create and share version.txt file'
outputs:
  version:
    description: "version number"
    value: ${{ steps.reading-version.outputs.version }}

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - name: getting node version
      if: hashFiles('package.json') != ''
      run: |
        VERSION=$(grep 'version' package.json | cut -f2 -d":" | cut -f2 -d\")
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash

    - name: getting python version
      if: hashFiles('pyproject.toml') != ''
      run: |
        VERSION=$(grep -E '^version' pyproject.toml | cut -f2 -d":" | cut -f2 -d\")
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash

    - name: reading version
      id: reading-version
      run: |
        echo "${PROJECT_VERSION}" > version.txt
        echo "version=$(echo ${PROJECT_VERSION})" >> $GITHUB_OUTPUT
      shell: bash
      env:
        PROJECT_VERSION: ${{ env.VERSION }}

    - name: upload version
      if: hashFiles('version.txt') != ''
      uses: actions/cache@v5
      with:
        path: version.txt
        key: ${{ runner.os }}-version

