name: 'actions/test-coverage'
description: 'Coverage project'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - uses: yadickson/actions/cache-load@main

    - name: testing coverage node project
      if: hashFiles('package.json') != ''
      run: npm run test:coverage
      id: testing-node
      continue-on-error: true
      shell: bash

    - name: testing coverage python project
      if: hashFiles('pyproject.toml') != ''
      run: |
        pip install .[dev]
        export PATH=$PATH:/app/.local/bin
        poetry run poe test:coverage
      id: testing-python
      continue-on-error: true
      shell: bash

    - name: upload unit test report
      uses: actions/upload-artifact@v6
      with:
        name: coverage
        path: reports/coverage
        retention-days: 1

    - name: testing coverage node project fail
      if: steps.testing-node.outcome == 'failure'
      run: exit 1
      shell: bash

    - name: testing coverage python project fail
      if: steps.testing-python.outcome == 'failure'
      run: exit 1
      shell: bash
