name: 'actions/install'
description: 'Install all dependencies'

branding:
  icon: 'box'
  color: 'green'

runs:
  using: "composite"
  steps:

    - id: project_type
      uses: yadickson/actions-steps/project-type@v1

    - if: ${{ steps.project_type.outputs.type }} == 'node'
      uses: yadickson/actions-steps/project-install/node@v1

    - if: ${{ steps.project_type.outputs.type }} == 'python'
      uses: yadickson/actions-steps/project-install/python@v1

    - uses: yadickson/actions-steps/cache-dependencies@v1
